### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by ChrisBeeley** [hoga-it/healthdown#19]
This is so awesome I had to ring my colleague immediately to show them because I love it so much!

I noticed there isn't an open source licence- is this a deliberate decision? If so, thanks for sharing anyway, but if not it would be super cool if you posted one so I could look at remixing some of the great stuff you're doing with `{leafdown}`.

Thank you!

**Comment by petergandenberger** [comment]
Thank you for your feedback, we are happy that you like our package.

The package itself and the code ist completely open source!
However the shapes used for the map are not; [The data are freely available for academic use and other non-commercial use. Redistribution, or commercial use, is not allowed without prior permission.](https://gadm.org/license.html)

Hence we did not include an open source license. 

We are happy to help if you have any questions regarding this project or the leafdown package itself!

**Comment by ChrisBeeley** [comment]
Aha, that makes sense, thank you. Happily for me, I only want the code, not the map, because I am in the UK.

I hope to sell this project to my bosses and when I do I will be remixing what you've done here with UK data and maps, I will of course link prominently to this repo and your package if I do so.

Thanks!
